const RAY_API = 'https://ray.tinte.dev/api/v1/screenshot';
const DEFAULT_TITLE = 'code.js';
const TIMEOUT_MS = 60000;
const EXT_LANG = {
   js: 'javascript',
   mjs: 'javascript',
   cjs: 'javascript',
   ts: 'typescript',
   tsx: 'tsx',
   jsx: 'javascript',
   py: 'python',
   rs: 'rust',
   go: 'go',
   html: 'html',
   css: 'css',
   json: 'json',
   sh: 'bash',
   bash: 'bash',
   sql: 'sql',
   java: 'java',
   cpp: 'cpp',
   cc: 'cpp',
   rb: 'ruby',
   swift: 'swift',
   kt: 'kotlin'
};
function detectLanguage(filename) {
   const ext = filename?.split('.').pop()?.toLowerCase();
   return EXT_LANG[ext] || 'javascript';
}
async function resolveInput(m) {
   const q = m.quoted;
   if (!q) {
      return {
         error: 'Balas teks atau document berisi code yang ingin diubah jadi gambar.'
      };
   }
   if (q.type === 'documentMessage') {
      let code;
      try {
         code = Buffer.from(await q.download())
            .toString('utf8')
            .trim();
      } catch (err) {
         console.error('[C2I] download error:', err?.message || err);
         return {
            error: 'Gagal mengunduh document.'
         };
      }
      if (!code)
         return {
            error: 'File yang dibalas kosong.'
         };
      const title = q.full?.documentMessage?.fileName || DEFAULT_TITLE;
      return {
         code,
         title,
         language: detectLanguage(title)
      };
   }
   const code = q.text?.trim();
   if (!code)
      return {
         error: 'Pesan yang dibalas tidak memiliki teks atau code.'
      };
   return {
      code,
      title: DEFAULT_TITLE,
      language: detectLanguage(DEFAULT_TITLE)
   };
}
async function generateImage(code, title, language) {
   const controller = new AbortController();
   const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);
   let res;
   try {
      res = await fetch(RAY_API, {
         method: 'POST',
         headers: {
            'Content-Type': 'application/json'
         },
         body: JSON.stringify({
            code,
            language,
            theme: 'crafter-station',
            padding: 8,
            fontSize: 18,
            lineNumbers: true,
            title,
            background: 'ocean'
         }),
         signal: controller.signal
      });
   } catch (err) {
      if (err?.name === 'AbortError') {
         throw new Error('Request timeout setelah 1 menit.');
      }
      throw err;
   } finally {
      clearTimeout(timer);
   }
   if (!/^image\//.test(res.headers.get('content-type') || '')) {
      const detail = await res.text().catch(() => '');
      throw new Error(
         `API error ${res.status}${detail ? `: ${detail.slice(0, 300)}` : ''}`
      );
   }
   return Buffer.from(await res.arrayBuffer());
}
exports.default = {
   tags: 'tools',
   help: ['c2i', 'tocarbon', '2carbon', 'carbonify'],
   command: ['c2i', 'tocarbon', '2carbon', 'carbonify'],
   start: async (m, { 
      sock, 
      args 
   }) => {
      const input = await resolveInput(m);
      if (input.error) return m.reply(input.error);
      const asThumbnail = args.some((a) => a.toLowerCase() === '-ct');
      let buffer;
      try {
         buffer = await generateImage(input.code, input.title, input.language);
      } catch (err) {
         console.error('[C2I] error:', err?.message || err);
         return m.reply('Gagal membuat gambar dari code, coba lagi nanti.');
      }
      if (asThumbnail) {
         let meta;
         try {
            meta = await sock.uploadThumbnail(buffer);
         } catch (err) {
            console.error('[C2I] thumbnail upload error:', err?.message || err);
            return m.reply('Gagal mengunggah thumbnail, coba lagi nanti.');
         }
         const targetUrl = 'https://chat.whatsapp.com';
         return m.reply({
            extendedTextMessage: {
               title: input.title,
               description: `Language: ${input.language}`,
               text: `${targetUrl}\n\nGenerated by ${setting.botName}.`,
               matchedText: targetUrl,
               previewType: 0,
               inviteLinkGroupTypeV2: 0,
               ...meta
            }
         });
      }
      return m.reply({
         type: 'image',
         media: buffer,
         mimetype: 'image/png',
         caption: `✅ ${input.title}`
      });
   }
}